from latent_action_model.genie.modules.lam import UncontrolledDINOLatentActionModel, ControllableDINOLatentActionModel
from latent_action_model.genie.modules.lam_visual_vq import VisualVQDINOLatentActionModel
